name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        options: >-
          --health-cmd "rabbitmq-diagnostics -q ping"
          --health-interval 30s
          --health-timeout 30s
          --health-retries 3

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17 for Project
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Wait for RabbitMQ to be ready
        run: |
          echo "Waiting for RabbitMQ to be ready..."
          until curl -f http://localhost:15672/api/overview -u guest:guest; do
            echo "RabbitMQ is unavailable - sleeping"
            sleep 5
          done
          echo "RabbitMQ is up and running!"

      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25
        with:
          arguments: build
        env:
          RABBITMQ_HOST: localhost
          RABBITMQ_PORT: 5672
          RABBITMQ_USERNAME: guest
          RABBITMQ_PASSWORD: guest

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Relay
          path: build/libs/relay-*.jar